server:
  port: 8080

spring:
  application:
    name: knowledge-graph
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.179.153:3306/knowledge-graph?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Li123456.
  neo4j:
    #    uri: bolt://192.168.179.129:7687
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: li123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

csv:
  upload_path: D:\GitStorage\knowledge-graph\src\main\resources\static\csv\